package ftd2;


import java.util.Arrays;
import java.util.List;

import com.sun.jna.NativeLong;
import com.sun.jna.Structure;

import ftd2.Ftd2xx.FT_HANDLE;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_DEVICE_LIST_INFO_NODE extends Structure {
	public NativeLong Flags;
	public NativeLong Type;
	public NativeLong ID;
	public int LocId;
	/// C type : char[16]
	public byte[] SerialNumber = new byte[16];
	/// C type : char[64]
	public byte[] Description = new byte[64];
	/// C type : FT_HANDLE
	public FT_HANDLE ftHandle;
	public FT_DEVICE_LIST_INFO_NODE() {
		super();
		//getFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"Flags", "Type", "ID", "LocId", "SerialNumber", "Description", "ftHandle"});
	}
	/**
	 * @param SerialNumber C type : char[16]<br>
	 * @param Description C type : char[64]<br>
	 * @param ftHandle C type : FT_HANDLE
	 */
	public FT_DEVICE_LIST_INFO_NODE(NativeLong Flags, NativeLong Type, NativeLong ID, int LocId, byte SerialNumber[], byte Description[], FT_HANDLE ftHandle) {
		super();
		this.Flags = Flags;
		this.Type = Type;
		this.ID = ID;
		this.LocId = LocId;
		if (SerialNumber.length != this.SerialNumber.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.SerialNumber = SerialNumber;
		if (Description.length != this.Description.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.Description = Description;
		this.ftHandle = ftHandle;
		//initFieldOrder();
	}
	public static class ByReference extends FT_DEVICE_LIST_INFO_NODE implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_DEVICE_LIST_INFO_NODE implements Structure.ByValue {
		
	};
}
