package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;

import ftd2.Ftd2xx.UCHAR;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_EEPROM_232H extends Structure {
	/**
	 * Common header<br>
	 * common elements for all device EEPROMs<br>
	 * C type : FT_EEPROM_HEADER
	 */
	public FT_EEPROM_HEADER common;
	/**
	 * Drive options<br>
	 * non-zero if AC bus pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR ACSlowSlew;
	/**
	 * non-zero if AC bus pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR ACSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR ACDriveCurrent;
	/**
	 * non-zero if AD bus pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR ADSlowSlew;
	/**
	 * non-zero if AD bus pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR ADSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR ADDriveCurrent;
	/**
	 * CBUS options<br>
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus0;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus1;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus2;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus3;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus4;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus5;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus6;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus7;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus8;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus9;
	/**
	 * FT1248 options<br>
	 * FT1248 clock polarity - clock idle high (1) or clock idle low (0)<br>
	 * C type : UCHAR
	 */
	public UCHAR FT1248Cpol;
	/**
	 * FT1248 data is LSB (1) or MSB (0)<br>
	 * C type : UCHAR
	 */
	public UCHAR FT1248Lsb;
	/**
	 * FT1248 flow control enable<br>
	 * C type : UCHAR
	 */
	public UCHAR FT1248FlowControl;
	/**
	 * Hardware options<br>
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR IsFifo;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR IsFifoTar;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR IsFastSer;
	/**
	 * non-zero if interface is FT1248<br>
	 * C type : UCHAR
	 */
	public UCHAR IsFT1248;
	/// C type : UCHAR
	public UCHAR PowerSaveEnable;
	/**
	 * Driver option<br>
	 * C type : UCHAR
	 */
	public UCHAR DriverType;
	public FT_EEPROM_232H() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"common", "ACSlowSlew", "ACSchmittInput", "ACDriveCurrent", "ADSlowSlew", "ADSchmittInput", "ADDriveCurrent", "Cbus0", "Cbus1", "Cbus2", "Cbus3", "Cbus4", "Cbus5", "Cbus6", "Cbus7", "Cbus8", "Cbus9", "FT1248Cpol", "FT1248Lsb", "FT1248FlowControl", "IsFifo", "IsFifoTar", "IsFastSer", "IsFT1248", "PowerSaveEnable", "DriverType"});
	}
	public static class ByReference extends FT_EEPROM_232H implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_EEPROM_232H implements Structure.ByValue {
		
	};
}
