package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_EEPROM_232B extends Structure {
	/**
	 * Common header<br>
	 * common elements for all device EEPROMs<br>
	 * C type : FT_EEPROM_HEADER
	 */
	public FT_EEPROM_HEADER common;
	public FT_EEPROM_232B() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"common"});
	}
	/**
	 * @param common Common header<br>
	 * common elements for all device EEPROMs<br>
	 * C type : FT_EEPROM_HEADER
	 */
	public FT_EEPROM_232B(FT_EEPROM_HEADER common) {
		super();
		this.common = common;
		//initFieldOrder();
	}
	public static class ByReference extends FT_EEPROM_232B implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_EEPROM_232B implements Structure.ByValue {
		
	};
}
