package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;

import ftd2.Ftd2xx.UCHAR;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_EEPROM_232R extends Structure {
	/**
	 * Common header<br>
	 * common elements for all device EEPROMs<br>
	 * C type : FT_EEPROM_HEADER
	 */
	public FT_EEPROM_HEADER common;
	/**
	 * Drive options<br>
	 * non-zero if interface is high current<br>
	 * C type : UCHAR
	 */
	public UCHAR IsHighCurrent;
	/**
	 * Hardware options<br>
	 * Use External Oscillator<br>
	 * C type : UCHAR
	 */
	public UCHAR UseExtOsc;
	/**
	 * non-zero if invert TXD<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertTXD;
	/**
	 * non-zero if invert RXD<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertRXD;
	/**
	 * non-zero if invert RTS<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertRTS;
	/**
	 * non-zero if invert CTS<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertCTS;
	/**
	 * non-zero if invert DTR<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertDTR;
	/**
	 * non-zero if invert DSR<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertDSR;
	/**
	 * non-zero if invert DCD<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertDCD;
	/**
	 * non-zero if invert RI<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertRI;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus0;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus1;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus2;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus3;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus4;
	/**
	 * Driver option<br>
	 * C type : UCHAR
	 */
	public UCHAR DriverType;
	public FT_EEPROM_232R() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"common", "IsHighCurrent", "UseExtOsc", "InvertTXD", "InvertRXD", "InvertRTS", "InvertCTS", "InvertDTR", "InvertDSR", "InvertDCD", "InvertRI", "Cbus0", "Cbus1", "Cbus2", "Cbus3", "Cbus4", "DriverType"});
	}
	public static class ByReference extends FT_EEPROM_232R implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_EEPROM_232R implements Structure.ByValue {
		
	};
}
