package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;

import ftd2.Ftd2xx.UCHAR;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_EEPROM_2232H extends Structure {
	/**
	 * Common header<br>
	 * common elements for all device EEPROMs<br>
	 * C type : FT_EEPROM_HEADER
	 */
	public FT_EEPROM_HEADER common;
	/**
	 * Drive options<br>
	 * non-zero if AL pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR ALSlowSlew;
	/**
	 * non-zero if AL pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR ALSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR ALDriveCurrent;
	/**
	 * non-zero if AH pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR AHSlowSlew;
	/**
	 * non-zero if AH pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR AHSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR AHDriveCurrent;
	/**
	 * non-zero if BL pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR BLSlowSlew;
	/**
	 * non-zero if BL pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR BLSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR BLDriveCurrent;
	/**
	 * non-zero if BH pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR BHSlowSlew;
	/**
	 * non-zero if BH pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR BHSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR BHDriveCurrent;
	/**
	 * Hardware options<br>
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsFifo;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsFifoTar;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsFastSer;
	/**
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsFifo;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsFifoTar;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsFastSer;
	/**
	 * non-zero if using BCBUS7 to save power for self-powered designs<br>
	 * C type : UCHAR
	 */
	public UCHAR PowerSaveEnable;
	/**
	 * Driver option<br>
	 * C type : UCHAR
	 */
	public UCHAR ADriverType;
	/// C type : UCHAR
	public UCHAR BDriverType;
	public FT_EEPROM_2232H() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"common", "ALSlowSlew", "ALSchmittInput", "ALDriveCurrent", "AHSlowSlew", "AHSchmittInput", "AHDriveCurrent", "BLSlowSlew", "BLSchmittInput", "BLDriveCurrent", "BHSlowSlew", "BHSchmittInput", "BHDriveCurrent", "AIsFifo", "AIsFifoTar", "AIsFastSer", "BIsFifo", "BIsFifoTar", "BIsFastSer", "PowerSaveEnable", "ADriverType", "BDriverType"});
	}
	public static class ByReference extends FT_EEPROM_2232H implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_EEPROM_2232H implements Structure.ByValue {
		
	};
}
