package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;

import ftd2.Ftd2xx.UCHAR;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_EEPROM_2232 extends Structure {
	/**
	 * Common header<br>
	 * common elements for all device EEPROMs<br>
	 * C type : FT_EEPROM_HEADER
	 */
	public FT_EEPROM_HEADER common;
	/**
	 * Drive options<br>
	 * non-zero if interface is high current<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsHighCurrent;
	/**
	 * non-zero if interface is high current<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsHighCurrent;
	/**
	 * Hardware options<br>
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsFifo;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsFifoTar;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsFastSer;
	/**
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsFifo;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsFifoTar;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsFastSer;
	/**
	 * Driver option<br>
	 * C type : UCHAR
	 */
	public UCHAR ADriverType;
	/// C type : UCHAR
	public UCHAR BDriverType;
	public FT_EEPROM_2232() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"common", "AIsHighCurrent", "BIsHighCurrent", "AIsFifo", "AIsFifoTar", "AIsFastSer", "BIsFifo", "BIsFifoTar", "BIsFastSer", "ADriverType", "BDriverType"});
	}
	public static class ByReference extends FT_EEPROM_2232 implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_EEPROM_2232 implements Structure.ByValue {
		
	};
}
