package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;

import ftd2.Ftd2xx.UCHAR;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_EEPROM_4232H extends Structure {
	/**
	 * Common header<br>
	 * common elements for all device EEPROMs<br>
	 * C type : FT_EEPROM_HEADER
	 */
	public FT_EEPROM_HEADER common;
	/**
	 * Drive options<br>
	 * non-zero if A pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR ASlowSlew;
	/**
	 * non-zero if A pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR ASchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR ADriveCurrent;
	/**
	 * non-zero if B pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR BSlowSlew;
	/**
	 * non-zero if B pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR BSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR BDriveCurrent;
	/**
	 * non-zero if C pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR CSlowSlew;
	/**
	 * non-zero if C pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR CSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR CDriveCurrent;
	/**
	 * non-zero if D pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR DSlowSlew;
	/**
	 * non-zero if D pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR DSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR DDriveCurrent;
	/**
	 * Hardware options<br>
	 * non-zero if port A uses RI as RS485 TXDEN<br>
	 * C type : UCHAR
	 */
	public UCHAR ARIIsTXDEN;
	/**
	 * non-zero if port B uses RI as RS485 TXDEN<br>
	 * C type : UCHAR
	 */
	public UCHAR BRIIsTXDEN;
	/**
	 * non-zero if port C uses RI as RS485 TXDEN<br>
	 * C type : UCHAR
	 */
	public UCHAR CRIIsTXDEN;
	/**
	 * non-zero if port D uses RI as RS485 TXDEN<br>
	 * C type : UCHAR
	 */
	public UCHAR DRIIsTXDEN;
	/**
	 * Driver option<br>
	 * C type : UCHAR
	 */
	public UCHAR ADriverType;
	/// C type : UCHAR
	public UCHAR BDriverType;
	/// C type : UCHAR
	public UCHAR CDriverType;
	/// C type : UCHAR
	public UCHAR DDriverType;
	public FT_EEPROM_4232H() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"common", "ASlowSlew", "ASchmittInput", "ADriveCurrent", "BSlowSlew", "BSchmittInput", "BDriveCurrent", "CSlowSlew", "CSchmittInput", "CDriveCurrent", "DSlowSlew", "DSchmittInput", "DDriveCurrent", "ARIIsTXDEN", "BRIIsTXDEN", "CRIIsTXDEN", "DRIIsTXDEN", "ADriverType", "BDriverType", "CDriverType", "DDriverType"});
	}
	public static class ByReference extends FT_EEPROM_4232H implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_EEPROM_4232H implements Structure.ByValue {
		
	};
}
