package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.NativeLong;
import com.sun.jna.Structure;

import ftd2.Ftd2xx.UCHAR;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_EEPROM_HEADER extends Structure {
	/**
	 * FTxxxx device type to be programmed<br>
	 * C type : FT_DEVICE
	 */
	public NativeLong deviceType;
	/**
	 * Device descriptor options<br>
	 * 0x0403
	 */
	public short VendorId;
	/// 0x6001
	public short ProductId;
	/**
	 * non-zero if serial number to be used<br>
	 * C type : UCHAR
	 */
	public UCHAR SerNumEnable;
	/**
	 * Config descriptor options<br>
	 * 0 < MaxPower <= 500
	 */
	public short MaxPower;
	/**
	 * 0 = bus powered, 1 = self powered<br>
	 * C type : UCHAR
	 */
	public UCHAR SelfPowered;
	/**
	 * 0 = not capable, 1 = capable<br>
	 * C type : UCHAR
	 */
	public UCHAR RemoteWakeup;
	/**
	 * Hardware options<br>
	 * non-zero if pull down in suspend enabled<br>
	 * C type : UCHAR
	 */
	public UCHAR PullDownEnable;
	public FT_EEPROM_HEADER() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"deviceType", "VendorId", "ProductId", "SerNumEnable", "MaxPower", "SelfPowered", "RemoteWakeup", "PullDownEnable"});
	}
	/**
	 * @param deviceType FTxxxx device type to be programmed<br>
	 * C type : FT_DEVICE<br>
	 * @param VendorId Device descriptor options<br>
	 * 0x0403<br>
	 * @param ProductId 0x6001<br>
	 * @param SerNumEnable non-zero if serial number to be used<br>
	 * C type : UCHAR<br>
	 * @param MaxPower Config descriptor options<br>
	 * 0 < MaxPower <= 500<br>
	 * @param SelfPowered 0 = bus powered, 1 = self powered<br>
	 * C type : UCHAR<br>
	 * @param RemoteWakeup 0 = not capable, 1 = capable<br>
	 * C type : UCHAR<br>
	 * @param PullDownEnable Hardware options<br>
	 * non-zero if pull down in suspend enabled<br>
	 * C type : UCHAR
	 */
	public FT_EEPROM_HEADER(NativeLong deviceType, short VendorId, short ProductId, UCHAR SerNumEnable, short MaxPower, UCHAR SelfPowered, UCHAR RemoteWakeup, UCHAR PullDownEnable) {
		super();
		this.deviceType = deviceType;
		this.VendorId = VendorId;
		this.ProductId = ProductId;
		this.SerNumEnable = SerNumEnable;
		this.MaxPower = MaxPower;
		this.SelfPowered = SelfPowered;
		this.RemoteWakeup = RemoteWakeup;
		this.PullDownEnable = PullDownEnable;
		//initFieldOrder();
	}
	public static class ByReference extends FT_EEPROM_HEADER implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_EEPROM_HEADER implements Structure.ByValue {
		
	};
}
