package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import ftd2.Ftd2xx.UCHAR;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FT_PROGRAM_DATA extends Structure {
	/// Header - must be 0x00000000
	public int Signature1;
	/// Header - must be 0xffffffff
	public int Signature2;
	/// Header - FT_PROGRAM_DATA version
	public int Version;
	/// 0x0403
	public short VendorId;
	/// 0x6001
	public short ProductId;
	/**
	 * "FTDI"<br>
	 * C type : char*
	 */
	public Pointer Manufacturer;
	/**
	 * "FT"<br>
	 * C type : char*
	 */
	public Pointer ManufacturerId;
	/**
	 * "USB HS Serial Converter"<br>
	 * C type : char*
	 */
	public Pointer Description;
	/**
	 * "FT000001" if fixed, or NULL<br>
	 * C type : char*
	 */
	public Pointer SerialNumber;
	/// 0 < MaxPower <= 500
	public short MaxPower;
	/// 0 = disabled, 1 = enabled
	public short PnP;
	/// 0 = bus powered, 1 = self powered
	public short SelfPowered;
	/// 0 = not capable, 1 = capable
	public short RemoteWakeup;
	/**
	 * non-zero if Rev4 chip, zero otherwise<br>
	 * C type : UCHAR
	 */
	public UCHAR Rev4;
	/**
	 * non-zero if in endpoint is isochronous<br>
	 * C type : UCHAR
	 */
	public UCHAR IsoIn;
	/**
	 * non-zero if out endpoint is isochronous<br>
	 * C type : UCHAR
	 */
	public UCHAR IsoOut;
	/**
	 * non-zero if pull down enabled<br>
	 * C type : UCHAR
	 */
	public UCHAR PullDownEnable;
	/**
	 * non-zero if serial number to be used<br>
	 * C type : UCHAR
	 */
	public UCHAR SerNumEnable;
	/**
	 * non-zero if chip uses USBVersion<br>
	 * C type : UCHAR
	 */
	public UCHAR USBVersionEnable;
	/// BCD (0x0200 => USB2)
	public short USBVersion;
	/**
	 * non-zero if Rev5 chip, zero otherwise<br>
	 * C type : UCHAR
	 */
	public UCHAR Rev5;
	/**
	 * non-zero if in endpoint is isochronous<br>
	 * C type : UCHAR
	 */
	public UCHAR IsoInA;
	/**
	 * non-zero if in endpoint is isochronous<br>
	 * C type : UCHAR
	 */
	public UCHAR IsoInB;
	/**
	 * non-zero if out endpoint is isochronous<br>
	 * C type : UCHAR
	 */
	public UCHAR IsoOutA;
	/**
	 * non-zero if out endpoint is isochronous<br>
	 * C type : UCHAR
	 */
	public UCHAR IsoOutB;
	/**
	 * non-zero if pull down enabled<br>
	 * C type : UCHAR
	 */
	public UCHAR PullDownEnable5;
	/**
	 * non-zero if serial number to be used<br>
	 * C type : UCHAR
	 */
	public UCHAR SerNumEnable5;
	/**
	 * non-zero if chip uses USBVersion<br>
	 * C type : UCHAR
	 */
	public UCHAR USBVersionEnable5;
	/// BCD (0x0200 => USB2)
	public short USBVersion5;
	/**
	 * non-zero if interface is high current<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsHighCurrent;
	/**
	 * non-zero if interface is high current<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsHighCurrent;
	/**
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR IFAIsFifo;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR IFAIsFifoTar;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR IFAIsFastSer;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsVCP;
	/**
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR IFBIsFifo;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR IFBIsFifoTar;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR IFBIsFastSer;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsVCP;
	/**
	 * Use External Oscillator<br>
	 * C type : UCHAR
	 */
	public UCHAR UseExtOsc;
	/**
	 * High Drive I/Os<br>
	 * C type : UCHAR
	 */
	public UCHAR HighDriveIOs;
	/**
	 * Endpoint size<br>
	 * C type : UCHAR
	 */
	public UCHAR EndpointSize;
	/**
	 * non-zero if pull down enabled<br>
	 * C type : UCHAR
	 */
	public UCHAR PullDownEnableR;
	/**
	 * non-zero if serial number to be used<br>
	 * C type : UCHAR
	 */
	public UCHAR SerNumEnableR;
	/**
	 * non-zero if invert TXD<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertTXD;
	/**
	 * non-zero if invert RXD<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertRXD;
	/**
	 * non-zero if invert RTS<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertRTS;
	/**
	 * non-zero if invert CTS<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertCTS;
	/**
	 * non-zero if invert DTR<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertDTR;
	/**
	 * non-zero if invert DSR<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertDSR;
	/**
	 * non-zero if invert DCD<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertDCD;
	/**
	 * non-zero if invert RI<br>
	 * C type : UCHAR
	 */
	public UCHAR InvertRI;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus0;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus1;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus2;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus3;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus4;
	/**
	 * non-zero if using D2XX driver<br>
	 * C type : UCHAR
	 */
	public UCHAR RIsD2XX;
	/**
	 * non-zero if pull down enabled<br>
	 * C type : UCHAR
	 */
	public UCHAR PullDownEnable7;
	/**
	 * non-zero if serial number to be used<br>
	 * C type : UCHAR
	 */
	public UCHAR SerNumEnable7;
	/**
	 * non-zero if AL pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR ALSlowSlew;
	/**
	 * non-zero if AL pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR ALSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR ALDriveCurrent;
	/**
	 * non-zero if AH pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR AHSlowSlew;
	/**
	 * non-zero if AH pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR AHSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR AHDriveCurrent;
	/**
	 * non-zero if BL pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR BLSlowSlew;
	/**
	 * non-zero if BL pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR BLSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR BLDriveCurrent;
	/**
	 * non-zero if BH pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR BHSlowSlew;
	/**
	 * non-zero if BH pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR BHSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR BHDriveCurrent;
	/**
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR IFAIsFifo7;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR IFAIsFifoTar7;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR IFAIsFastSer7;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsVCP7;
	/**
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR IFBIsFifo7;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR IFBIsFifoTar7;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR IFBIsFastSer7;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsVCP7;
	/**
	 * non-zero if using BCBUS7 to save power for self-powered designs<br>
	 * C type : UCHAR
	 */
	public UCHAR PowerSaveEnable;
	/**
	 * non-zero if pull down enabled<br>
	 * C type : UCHAR
	 */
	public UCHAR PullDownEnable8;
	/**
	 * non-zero if serial number to be used<br>
	 * C type : UCHAR
	 */
	public UCHAR SerNumEnable8;
	/**
	 * non-zero if A pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR ASlowSlew;
	/**
	 * non-zero if A pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR ASchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR ADriveCurrent;
	/**
	 * non-zero if B pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR BSlowSlew;
	/**
	 * non-zero if B pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR BSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR BDriveCurrent;
	/**
	 * non-zero if C pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR CSlowSlew;
	/**
	 * non-zero if C pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR CSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR CDriveCurrent;
	/**
	 * non-zero if D pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR DSlowSlew;
	/**
	 * non-zero if D pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR DSchmittInput;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR DDriveCurrent;
	/**
	 * non-zero if port A uses RI as RS485 TXDEN<br>
	 * C type : UCHAR
	 */
	public UCHAR ARIIsTXDEN;
	/**
	 * non-zero if port B uses RI as RS485 TXDEN<br>
	 * C type : UCHAR
	 */
	public UCHAR BRIIsTXDEN;
	/**
	 * non-zero if port C uses RI as RS485 TXDEN<br>
	 * C type : UCHAR
	 */
	public UCHAR CRIIsTXDEN;
	/**
	 * non-zero if port D uses RI as RS485 TXDEN<br>
	 * C type : UCHAR
	 */
	public UCHAR DRIIsTXDEN;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR AIsVCP8;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR BIsVCP8;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR CIsVCP8;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR DIsVCP8;
	/**
	 * non-zero if pull down enabled<br>
	 * C type : UCHAR
	 */
	public UCHAR PullDownEnableH;
	/**
	 * non-zero if serial number to be used<br>
	 * C type : UCHAR
	 */
	public UCHAR SerNumEnableH;
	/**
	 * non-zero if AC pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR ACSlowSlewH;
	/**
	 * non-zero if AC pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR ACSchmittInputH;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR ACDriveCurrentH;
	/**
	 * non-zero if AD pins have slow slew<br>
	 * C type : UCHAR
	 */
	public UCHAR ADSlowSlewH;
	/**
	 * non-zero if AD pins are Schmitt input<br>
	 * C type : UCHAR
	 */
	public UCHAR ADSchmittInputH;
	/**
	 * valid values are 4mA, 8mA, 12mA, 16mA<br>
	 * C type : UCHAR
	 */
	public UCHAR ADDriveCurrentH;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus0H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus1H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus2H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus3H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus4H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus5H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus6H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus7H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus8H;
	/**
	 * Cbus Mux control<br>
	 * C type : UCHAR
	 */
	public UCHAR Cbus9H;
	/**
	 * non-zero if interface is 245 FIFO<br>
	 * C type : UCHAR
	 */
	public UCHAR IsFifoH;
	/**
	 * non-zero if interface is 245 FIFO CPU target<br>
	 * C type : UCHAR
	 */
	public UCHAR IsFifoTarH;
	/**
	 * non-zero if interface is Fast serial<br>
	 * C type : UCHAR
	 */
	public UCHAR IsFastSerH;
	/**
	 * non-zero if interface is FT1248<br>
	 * C type : UCHAR
	 */
	public UCHAR IsFT1248H;
	/**
	 * FT1248 clock polarity - clock idle high (1) or clock idle low (0)<br>
	 * C type : UCHAR
	 */
	public UCHAR FT1248CpolH;
	/**
	 * FT1248 data is LSB (1) or MSB (0)<br>
	 * C type : UCHAR
	 */
	public UCHAR FT1248LsbH;
	/**
	 * FT1248 flow control enable<br>
	 * C type : UCHAR
	 */
	public UCHAR FT1248FlowControlH;
	/**
	 * non-zero if interface is to use VCP drivers<br>
	 * C type : UCHAR
	 */
	public UCHAR IsVCPH;
	/**
	 * non-zero if using ACBUS7 to save power for self-powered designs<br>
	 * C type : UCHAR
	 */
	public UCHAR PowerSaveEnableH;
	public FT_PROGRAM_DATA() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"Signature1", "Signature2", "Version", "VendorId", "ProductId", "Manufacturer", "ManufacturerId", "Description", "SerialNumber", "MaxPower", "PnP", "SelfPowered", "RemoteWakeup", "Rev4", "IsoIn", "IsoOut", "PullDownEnable", "SerNumEnable", "USBVersionEnable", "USBVersion", "Rev5", "IsoInA", "IsoInB", "IsoOutA", "IsoOutB", "PullDownEnable5", "SerNumEnable5", "USBVersionEnable5", "USBVersion5", "AIsHighCurrent", "BIsHighCurrent", "IFAIsFifo", "IFAIsFifoTar", "IFAIsFastSer", "AIsVCP", "IFBIsFifo", "IFBIsFifoTar", "IFBIsFastSer", "BIsVCP", "UseExtOsc", "HighDriveIOs", "EndpointSize", "PullDownEnableR", "SerNumEnableR", "InvertTXD", "InvertRXD", "InvertRTS", "InvertCTS", "InvertDTR", "InvertDSR", "InvertDCD", "InvertRI", "Cbus0", "Cbus1", "Cbus2", "Cbus3", "Cbus4", "RIsD2XX", "PullDownEnable7", "SerNumEnable7", "ALSlowSlew", "ALSchmittInput", "ALDriveCurrent", "AHSlowSlew", "AHSchmittInput", "AHDriveCurrent", "BLSlowSlew", "BLSchmittInput", "BLDriveCurrent", "BHSlowSlew", "BHSchmittInput", "BHDriveCurrent", "IFAIsFifo7", "IFAIsFifoTar7", "IFAIsFastSer7", "AIsVCP7", "IFBIsFifo7", "IFBIsFifoTar7", "IFBIsFastSer7", "BIsVCP7", "PowerSaveEnable", "PullDownEnable8", "SerNumEnable8", "ASlowSlew", "ASchmittInput", "ADriveCurrent", "BSlowSlew", "BSchmittInput", "BDriveCurrent", "CSlowSlew", "CSchmittInput", "CDriveCurrent", "DSlowSlew", "DSchmittInput", "DDriveCurrent", "ARIIsTXDEN", "BRIIsTXDEN", "CRIIsTXDEN", "DRIIsTXDEN", "AIsVCP8", "BIsVCP8", "CIsVCP8", "DIsVCP8", "PullDownEnableH", "SerNumEnableH", "ACSlowSlewH", "ACSchmittInputH", "ACDriveCurrentH", "ADSlowSlewH", "ADSchmittInputH", "ADDriveCurrentH", "Cbus0H", "Cbus1H", "Cbus2H", "Cbus3H", "Cbus4H", "Cbus5H", "Cbus6H", "Cbus7H", "Cbus8H", "Cbus9H", "IsFifoH", "IsFifoTarH", "IsFastSerH", "IsFT1248H", "FT1248CpolH", "FT1248LsbH", "FT1248FlowControlH", "IsVCPH", "PowerSaveEnableH"});
	}
	public static class ByReference extends FT_PROGRAM_DATA implements Structure.ByReference {
		
	};
	public static class ByValue extends FT_PROGRAM_DATA implements Structure.ByValue {
		
	};
}
