package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FTCOMSTAT extends Structure {
	/// Conversion Error : fCtsHold:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fDsrHold:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fRlsdHold:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fXoffHold:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fXoffSent:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fEof:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fTxim:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fReserved:25 (This runtime does not support bit fields : JNA)
	public int cbInQue;
	public int cbOutQue;
	public FTCOMSTAT() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"cbInQue", "cbOutQue"});
	}
	public FTCOMSTAT(int cbInQue, int cbOutQue) {
		super();
		this.cbInQue = cbInQue;
		this.cbOutQue = cbOutQue;
		//initFieldOrder();
	}
	public static class ByReference extends FTCOMSTAT implements Structure.ByReference {
		
	};
	public static class ByValue extends FTCOMSTAT implements Structure.ByValue {
		
	};
}
