package ftd2;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Platform;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.NativeLongByReference;
import com.sun.jna.ptr.PointerByReference;

/**
 * JNA Wrapper for library <b>ftd2xx</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Ftd2xx extends Library {
	public static final String JNA_LIBRARY_NAME = 
			(
					(Platform.isWindows() && System.getProperty("os.arch").contains("86")) ? 
							"ftd2xx" :
					(Platform.isWindows() && System.getProperty("os.arch").contains("64")) ?
							"ftd2xx64" : 
					(Platform.isLinux() && System.getProperty("os.arch").contains("86")) ?
							"ftd2xx" :
					(Platform.isLinux() && System.getProperty("os.arch").contains("64")) ?
							"ftd2xx" :
					(Platform.isMac() && System.getProperty("os.arch").contains("86")) ?
							"ftd2xx" :
					(Platform.isMac() && System.getProperty("os.arch").contains("64")) ?
							"ftd2xx" :
					"Unknow"
			);
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Ftd2xx.JNA_LIBRARY_NAME);
	public static final Ftd2xx INSTANCE = (Ftd2xx)Native.loadLibrary(Ftd2xx.JNA_LIBRARY_NAME, 
			Platform.isWindows() ? Ftd2xxWin.class : Ftd2xx.class);
	public static final int FT_OK = (int)0;
	public static final int FT_INVALID_HANDLE = (int)1;
	public static final int FT_DEVICE_NOT_FOUND = (int)2;
	public static final int FT_DEVICE_NOT_OPENED = (int)3;
	public static final int FT_IO_ERROR = (int)4;
	public static final int FT_INSUFFICIENT_RESOURCES = (int)5;
	public static final int FT_INVALID_PARAMETER = (int)6;
	public static final int FT_INVALID_BAUD_RATE = (int)7;
	public static final int FT_DEVICE_NOT_OPENED_FOR_ERASE = (int)8;
	public static final int FT_DEVICE_NOT_OPENED_FOR_WRITE = (int)9;
	public static final int FT_FAILED_TO_WRITE_DEVICE = (int)10;
	public static final int FT_EEPROM_READ_FAILED = (int)11;
	public static final int FT_EEPROM_WRITE_FAILED = (int)12;
	public static final int FT_EEPROM_ERASE_FAILED = (int)13;
	public static final int FT_EEPROM_NOT_PRESENT = (int)14;
	public static final int FT_EEPROM_NOT_PROGRAMMED = (int)15;
	public static final int FT_INVALID_ARGS = (int)16;
	public static final int FT_NOT_SUPPORTED = (int)17;
	public static final int FT_OTHER_ERROR = (int)18;
	public static final int FT_DEVICE_LIST_NOT_READY = (int)19;
	public static final int FT_DEVICE_BM = (int)0;
	public static final int FT_DEVICE_AM = (int)1;
	public static final int FT_DEVICE_100AX = (int)2;
	public static final int FT_DEVICE_UNKNOWN = (int)3;
	public static final int FT_DEVICE_2232C = (int)4;
	public static final int FT_DEVICE_232R = (int)5;
	public static final int FT_DEVICE_2232H = (int)6;
	public static final int FT_DEVICE_4232H = (int)7;
	public static final int FT_DEVICE_232H = (int)8;
	public static final int FT_DEVICE_X_SERIES = (int)9;
	public static final int FT_FLAGS_OPENED = (int)1;
	public static final int FT_FLAGS_HISPEED = (int)2;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_TXLED = (int)2;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_CLK7_5 = (int)12;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_600 = (int)600;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BITMODE_MPSSE = (int)2;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_CLK6 = (int)9;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_FLOW_DTR_DSR = (int)512;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_14400 = (int)14400;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_DRIVER_TYPE_VCP = (int)1;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_TXLED = (int)3;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_SLEEP = (int)5;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_BCD_CHARGER = (int)13;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_PWREN = (int)4;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_BITBANG_RD = (int)12;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_TXRXLED = (int)3;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_PURGE_RX = (int)1;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_LIST_NUMBER_ONLY = (int)-2147483648;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_SLEEP = (int)5;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_VBUS_SENSE = (int)17;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_CLK6 = (int)12;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_TXDEN = (int)9;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_230400 = (int)230400;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_921600 = (int)921600;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BITMODE_SYNC_BITBANG = (int)4;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_EVENT_LINE_STATUS = (int)4;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_300 = (int)300;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_OPEN_BY_SERIAL_NUMBER = (int)1;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_TXLED = (int)1;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BITMODE_MCU_HOST = (int)8;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_I2C_TXE = (int)15;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_CLK48 = (int)6;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_BITBANG_RD = (int)19;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_TXDEN = (int)0;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_TRISTATE = (int)0;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_57600 = (int)57600;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_OPEN_BY_DESCRIPTION = (int)2;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_1200 = (int)1200;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_DRIVER_TYPE_D2XX = (int)0;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_LIST_ALL = (int)536870912;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_IOMODE = (int)8;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_2400 = (int)2400;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_LIST_BY_INDEX = (int)1073741824;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_115200 = (int)115200;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_KEEP_AWAKE = (int)21;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_CLK24 = (int)10;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_FLOW_RTS_CTS = (int)256;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_9600 = (int)9600;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_DEFAULT_TX_TIMEOUT = (int)300;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_EVENT_MODEM_STATUS = (int)2;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_PWRON = (int)1;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BITMODE_SYNC_FIFO = (int)64;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_PWREN = (int)4;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_OPEN_BY_LOCATION = (int)4;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_BITBANG_WR = (int)18;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_TIMESTAMP = (int)20;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_RXLED = (int)2;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_DRIVE_0 = (int)6;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_TXRXLED = (int)3;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_DRIVE_1 = (int)7;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_CLK24 = (int)7;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_CLK12 = (int)11;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_FLOW_XON_XOFF = (int)1024;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_CLK30 = (int)10;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_FLOW_NONE = (int)0;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_19200 = (int)19200;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_RXLED = (int)2;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_BITBANG_WR = (int)11;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_CLK12 = (int)8;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_I2C_RXF = (int)16;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_PURGE_TX = (int)2;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_EVENT_RXCHAR = (int)1;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_IOMODE = (int)10;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_RXLED = (int)1;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BITMODE_ASYNC_BITBANG = (int)1;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BITMODE_FAST_SERIAL = (int)16;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232R_CBUS_TXRXLED = (int)4;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_SLEEP = (int)5;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_4800 = (int)4800;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_DEFAULT_RX_TIMEOUT = (int)300;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_IOMODE = (int)8;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_460800 = (int)460800;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_LIST_MASK = (int)(-2147483648 | 1073741824 | 536870912);
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_BCD_CHARGER_N = (int)14;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_TRISTATE = (int)0;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_TXDEN = (int)9;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_232H_CBUS_CLK15 = (int)11;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BITMODE_RESET = (int)0;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BAUD_38400 = (int)38400;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_DRIVE_1 = (int)7;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_X_SERIES_CBUS_DRIVE_0 = (int)6;
	/// <i>native declaration : ftd2xx.h</i>
	public static final int FT_BITMODE_CBUS_BITBANG = (int)32;
	/// <i>native declaration : ftd2xx.h</i>
	/// <i>native declaration : ftd2xx.h</i>
	public interface PFT_EVENT_HANDLER extends Callback {
		void apply(int DWORD1, int DWORD2);
	};
	/**
	 * Original signature : <code>FT_STATUS FT_Open(int, FT_HANDLE*)</code><br>
	 * <i>native declaration : ftd2xx.h:292</i>
	 */
	NativeLong FT_Open(int deviceNumber, FT_HANDLE[] ftHandleTemp);
	/**
	 * Original signature : <code>FT_STATUS FT_OpenEx(PVOID, DWORD, FT_HANDLE*)</code><br>
	 * <i>native declaration : ftd2xx.h:298</i>
	 */
	NativeLong FT_OpenEx(Ftd2xx.PVOID pArg1, int Flags, Ftd2xx.FT_HANDLE pHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_ListDevices(PVOID, PVOID, DWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:305</i>
	 */
	//NativeLong fTListDevices(Ftd2xx.PVOID pArg1, Ftd2xx.PVOID pArg2, int Flags);
	NativeLong FT_ListDevices(Pointer pArg1, Pointer pArg2, int Flags);
	/**
	 * Original signature : <code>FT_STATUS FT_Close(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:312</i>
	 */
	NativeLong FT_Close(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_Read(FT_HANDLE, LPVOID, DWORD, LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:317</i>
	 */
	NativeLong FT_Read(Ftd2xx.FT_HANDLE ftHandle, byte[] b, int dwBytesToRead, IntByReference len);
	/**
	 * Original signature : <code>FT_STATUS FT_Write(FT_HANDLE, LPVOID, DWORD, LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:325</i>
	 */
	NativeLong FT_Write(Ftd2xx.FT_HANDLE ftHandle, byte[] b, int dwBytesToWrite, IntByReference len);
	/**
	 * Original signature : <code>FT_STATUS FT_IoCtl(FT_HANDLE, DWORD, LPVOID, DWORD, LPVOID, DWORD, LPDWORD, LPOVERLAPPED)</code><br>
	 * <i>native declaration : ftd2xx.h:333</i>
	 */
	NativeLong fTIoCtl(Ftd2xx.FT_HANDLE ftHandle, int dwIoControlCode, Ftd2xx.LPVOID lpInBuf, int nInBufSize, Ftd2xx.LPVOID lpOutBuf, int nOutBufSize, Ftd2xx.LPDWORD lpBytesReturned, Ftd2xx.LPOVERLAPPED lpOverlapped);
	/**
	 * Original signature : <code>FT_STATUS FT_SetBaudRate(FT_HANDLE, ULONG)</code><br>
	 * <i>native declaration : ftd2xx.h:345</i>
	 */
	NativeLong FT_SetBaudRate(Ftd2xx.FT_HANDLE ftHandle, int BaudRate);
	/**
	 * Original signature : <code>FT_STATUS FT_SetDivisor(FT_HANDLE, USHORT)</code><br>
	 * <i>native declaration : ftd2xx.h:351</i>
	 */
	NativeLong fTSetDivisor(Ftd2xx.FT_HANDLE ftHandle, short Divisor);
	/**
	 * Original signature : <code>FT_STATUS FT_SetDataCharacteristics(FT_HANDLE, UCHAR, UCHAR, UCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:357</i>
	 */
	NativeLong FT_SetDataCharacteristics(Ftd2xx.FT_HANDLE ftHandle, int wordLength, int stopBits, int parity);
	/**
	 * Original signature : <code>FT_STATUS FT_SetFlowControl(FT_HANDLE, USHORT, UCHAR, UCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:365</i>
	 */
	NativeLong FT_SetFlowControl(Ftd2xx.FT_HANDLE ftHandle, int flowControl, int xonChar, int xoffChar);
	/**
	 * Original signature : <code>FT_STATUS FT_ResetDevice(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:373</i>
	 */
	NativeLong fTResetDevice(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_SetDtr(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:378</i>
	 */
	NativeLong fTSetDtr(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_ClrDtr(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:383</i>
	 */
	NativeLong fTClrDtr(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_SetRts(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:388</i>
	 */
	NativeLong fTSetRts(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_ClrRts(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:393</i>
	 */
	NativeLong fTClrRts(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_GetModemStatus(FT_HANDLE, ULONG*)</code><br>
	 * <i>native declaration : ftd2xx.h:398</i>
	 */
	NativeLong fTGetModemStatus(Ftd2xx.FT_HANDLE ftHandle, NativeLongByReference pModemStatus);
	/**
	 * Original signature : <code>FT_STATUS FT_SetChars(FT_HANDLE, UCHAR, UCHAR, UCHAR, UCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:404</i>
	 */
	NativeLong fTSetChars(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.UCHAR EventChar, Ftd2xx.UCHAR EventCharEnabled, Ftd2xx.UCHAR ErrorChar, Ftd2xx.UCHAR ErrorCharEnabled);
	/**
	 * Original signature : <code>FT_STATUS FT_Purge(FT_HANDLE, ULONG)</code><br>
	 * <i>native declaration : ftd2xx.h:413</i>
	 */
	NativeLong FT_Purge(Ftd2xx.FT_HANDLE ftHandle, int mask);
	/**
	 * Original signature : <code>FT_STATUS FT_SetTimeouts(FT_HANDLE, ULONG, ULONG)</code><br>
	 * <i>native declaration : ftd2xx.h:419</i>
	 */
	NativeLong FT_SetTimeouts(Ftd2xx.FT_HANDLE ftHandle, int readTimeout, int writeTimeout);
	/**
	 * Original signature : <code>FT_STATUS FT_GetQueueStatus(FT_HANDLE, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:426</i><br>
	 * @deprecated use the safer methods {@link #fTGetQueueStatus(ftd2xx.Ftd2xxLibrary.FT_HANDLE, java.nio.IntBuffer)} and {@link #fTGetQueueStatus(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	NativeLong fTGetQueueStatus(Ftd2xx.FT_HANDLE ftHandle, IntByReference dwRxBytes);
	/**
	 * Original signature : <code>FT_STATUS FT_GetQueueStatus(FT_HANDLE, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:426</i>
	 */
	NativeLong fTGetQueueStatus(Ftd2xx.FT_HANDLE ftHandle, IntBuffer dwRxBytes);
	/**
	 * Original signature : <code>FT_STATUS FT_SetEventNotification(FT_HANDLE, DWORD, PVOID)</code><br>
	 * <i>native declaration : ftd2xx.h:432</i>
	 */
	NativeLong fTSetEventNotification(Ftd2xx.FT_HANDLE ftHandle, int Mask, Ftd2xx.PVOID Param);
	/**
	 * Original signature : <code>FT_STATUS FT_GetStatus(FT_HANDLE, DWORD*, DWORD*, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:439</i><br>
	 * @deprecated use the safer methods {@link #fTGetStatus(ftd2xx.Ftd2xxLibrary.FT_HANDLE, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #fTGetStatus(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	NativeLong fTGetStatus(Ftd2xx.FT_HANDLE ftHandle, IntByReference dwRxBytes, IntByReference dwTxBytes, IntByReference dwEventDWord);
	/**
	 * Original signature : <code>FT_STATUS FT_GetStatus(FT_HANDLE, DWORD*, DWORD*, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:439</i>
	 */
	NativeLong fTGetStatus(Ftd2xx.FT_HANDLE ftHandle, IntBuffer dwRxBytes, IntBuffer dwTxBytes, IntBuffer dwEventDWord);
	/**
	 * Original signature : <code>FT_STATUS FT_SetBreakOn(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:447</i>
	 */
	NativeLong fTSetBreakOn(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_SetBreakOff(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:452</i>
	 */
	NativeLong fTSetBreakOff(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_SetWaitMask(FT_HANDLE, DWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:457</i>
	 */
	NativeLong fTSetWaitMask(Ftd2xx.FT_HANDLE ftHandle, int Mask);
	/**
	 * Original signature : <code>FT_STATUS FT_WaitOnMask(FT_HANDLE, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:463</i><br>
	 * @deprecated use the safer methods {@link #fTWaitOnMask(ftd2xx.Ftd2xxLibrary.FT_HANDLE, java.nio.IntBuffer)} and {@link #fTWaitOnMask(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	NativeLong fTWaitOnMask(Ftd2xx.FT_HANDLE ftHandle, IntByReference Mask);
	/**
	 * Original signature : <code>FT_STATUS FT_WaitOnMask(FT_HANDLE, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:463</i>
	 */
	NativeLong fTWaitOnMask(Ftd2xx.FT_HANDLE ftHandle, IntBuffer Mask);
	/**
	 * Original signature : <code>FT_STATUS FT_GetEventStatus(FT_HANDLE, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:469</i><br>
	 * @deprecated use the safer methods {@link #fTGetEventStatus(ftd2xx.Ftd2xxLibrary.FT_HANDLE, java.nio.IntBuffer)} and {@link #fTGetEventStatus(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	NativeLong fTGetEventStatus(Ftd2xx.FT_HANDLE ftHandle, IntByReference dwEventDWord);
	/**
	 * Original signature : <code>FT_STATUS FT_GetEventStatus(FT_HANDLE, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:469</i>
	 */
	NativeLong fTGetEventStatus(Ftd2xx.FT_HANDLE ftHandle, IntBuffer dwEventDWord);
	/**
	 * Original signature : <code>FT_STATUS FT_ReadEE(FT_HANDLE, DWORD, LPWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:475</i>
	 */
	NativeLong fTReadEE(Ftd2xx.FT_HANDLE ftHandle, int dwWordOffset, Ftd2xx.LPWORD lpwValue);
	/**
	 * Original signature : <code>FT_STATUS FT_WriteEE(FT_HANDLE, DWORD, WORD)</code><br>
	 * <i>native declaration : ftd2xx.h:482</i>
	 */
	NativeLong fTWriteEE(Ftd2xx.FT_HANDLE ftHandle, int dwWordOffset, short wValue);
	/**
	 * Original signature : <code>FT_STATUS FT_EraseEE(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:489</i>
	 */
	NativeLong fTEraseEE(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_Program(FT_HANDLE, PFT_PROGRAM_DATA)</code><br>
	 * <i>native declaration : ftd2xx.h:658</i>
	 */
	NativeLong fTEEProgram(Ftd2xx.FT_HANDLE ftHandle, FT_PROGRAM_DATA pData);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_ProgramEx(FT_HANDLE, PFT_PROGRAM_DATA, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : ftd2xx.h:664</i><br>
	 * @deprecated use the safer methods {@link #fTEEProgramEx(ftd2xx.Ftd2xxLibrary.FT_HANDLE, ftd2xx.FT_PROGRAM_DATA, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer)} and {@link #fTEEProgramEx(ftd2xx.Ftd2xxLibrary.FT_HANDLE, ftd2xx.FT_PROGRAM_DATA, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	NativeLong fTEEProgramEx(Ftd2xx.FT_HANDLE ftHandle, FT_PROGRAM_DATA pData, Pointer Manufacturer, Pointer ManufacturerId, Pointer Description, Pointer SerialNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_ProgramEx(FT_HANDLE, PFT_PROGRAM_DATA, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : ftd2xx.h:664</i>
	 */
	NativeLong fTEEProgramEx(Ftd2xx.FT_HANDLE ftHandle, FT_PROGRAM_DATA pData, ByteBuffer Manufacturer, ByteBuffer ManufacturerId, ByteBuffer Description, ByteBuffer SerialNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_Read(FT_HANDLE, PFT_PROGRAM_DATA)</code><br>
	 * <i>native declaration : ftd2xx.h:674</i>
	 */
	NativeLong fTEERead(Ftd2xx.FT_HANDLE ftHandle, FT_PROGRAM_DATA pData);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_ReadEx(FT_HANDLE, PFT_PROGRAM_DATA, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : ftd2xx.h:680</i><br>
	 * @deprecated use the safer methods {@link #fTEEReadEx(ftd2xx.Ftd2xxLibrary.FT_HANDLE, ftd2xx.FT_PROGRAM_DATA, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer)} and {@link #fTEEReadEx(ftd2xx.Ftd2xxLibrary.FT_HANDLE, ftd2xx.FT_PROGRAM_DATA, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	NativeLong fTEEReadEx(Ftd2xx.FT_HANDLE ftHandle, FT_PROGRAM_DATA pData, Pointer Manufacturer, Pointer ManufacturerId, Pointer Description, Pointer SerialNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_ReadEx(FT_HANDLE, PFT_PROGRAM_DATA, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : ftd2xx.h:680</i>
	 */
	NativeLong fTEEReadEx(Ftd2xx.FT_HANDLE ftHandle, FT_PROGRAM_DATA pData, ByteBuffer Manufacturer, ByteBuffer ManufacturerId, ByteBuffer Description, ByteBuffer SerialNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_UASize(FT_HANDLE, LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:690</i>
	 */
	NativeLong fTEEUASize(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPDWORD lpdwSize);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_UAWrite(FT_HANDLE, PUCHAR, DWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:696</i>
	 */
	NativeLong fTEEUAWrite(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.PUCHAR pucData, int dwDataLen);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_UARead(FT_HANDLE, PUCHAR, DWORD, LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:703</i>
	 */
	NativeLong fTEEUARead(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.PUCHAR pucData, int dwDataLen, Ftd2xx.LPDWORD lpdwBytesRead);
	/**
	 * Original signature : <code>FT_STATUS FT_EEPROM_Read(FT_HANDLE, void*, DWORD, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : ftd2xx.h:926</i><br>
	 * @deprecated use the safer methods {@link #fTEEPROMRead(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.Pointer, int, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer)} and {@link #fTEEPROMRead(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.Pointer, int, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	NativeLong fTEEPROMRead(Ftd2xx.FT_HANDLE ftHandle, Pointer eepromData, int eepromDataSize, Pointer Manufacturer, Pointer ManufacturerId, Pointer Description, Pointer SerialNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_EEPROM_Read(FT_HANDLE, void*, DWORD, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : ftd2xx.h:926</i>
	 */
	NativeLong fTEEPROMRead(Ftd2xx.FT_HANDLE ftHandle, Pointer eepromData, int eepromDataSize, ByteBuffer Manufacturer, ByteBuffer ManufacturerId, ByteBuffer Description, ByteBuffer SerialNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_EEPROM_Program(FT_HANDLE, void*, DWORD, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : ftd2xx.h:938</i><br>
	 * @deprecated use the safer methods {@link #fTEEPROMProgram(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.Pointer, int, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer)} and {@link #fTEEPROMProgram(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.Pointer, int, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	NativeLong fTEEPROMProgram(Ftd2xx.FT_HANDLE ftHandle, Pointer eepromData, int eepromDataSize, Pointer Manufacturer, Pointer ManufacturerId, Pointer Description, Pointer SerialNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_EEPROM_Program(FT_HANDLE, void*, DWORD, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : ftd2xx.h:938</i>
	 */
	NativeLong fTEEPROMProgram(Ftd2xx.FT_HANDLE ftHandle, Pointer eepromData, int eepromDataSize, ByteBuffer Manufacturer, ByteBuffer ManufacturerId, ByteBuffer Description, ByteBuffer SerialNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_SetLatencyTimer(FT_HANDLE, UCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:950</i>
	 */
	NativeLong fTSetLatencyTimer(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.UCHAR ucLatency);
	/**
	 * Original signature : <code>FT_STATUS FT_GetLatencyTimer(FT_HANDLE, PUCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:956</i>
	 */
	NativeLong fTGetLatencyTimer(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.PUCHAR pucLatency);
	/**
	 * Original signature : <code>FT_STATUS FT_SetBitMode(FT_HANDLE, UCHAR, UCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:962</i>
	 */
	NativeLong FT_SetBitMode(Ftd2xx.FT_HANDLE ftHandle, int mask, int mode);
	/**
	 * Original signature : <code>FT_STATUS FT_GetBitMode(FT_HANDLE, PUCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:969</i>
	 */
	NativeLong FT_GetBitMode(Ftd2xx.FT_HANDLE ftHandle, IntByReference pucMode);
	/**
	 * Original signature : <code>FT_STATUS FT_SetUSBParameters(FT_HANDLE, ULONG, ULONG)</code><br>
	 * <i>native declaration : ftd2xx.h:975</i>
	 */
	NativeLong fTSetUSBParameters(Ftd2xx.FT_HANDLE ftHandle, NativeLong ulInTransferSize, NativeLong ulOutTransferSize);
	/**
	 * Original signature : <code>FT_STATUS FT_SetDeadmanTimeout(FT_HANDLE, ULONG)</code><br>
	 * <i>native declaration : ftd2xx.h:982</i>
	 */
	NativeLong fTSetDeadmanTimeout(Ftd2xx.FT_HANDLE ftHandle, NativeLong ulDeadmanTimeout);
	/**
	 * Original signature : <code>FT_STATUS FT_GetDeviceInfo(FT_HANDLE, FT_DEVICE*, LPDWORD, PCHAR, PCHAR, LPVOID)</code><br>
	 * <i>native declaration : ftd2xx.h:988</i>
	 */
	NativeLong fTGetDeviceInfo(Ftd2xx.FT_HANDLE ftHandle, NativeLongByReference lpftDevice, Ftd2xx.LPDWORD lpdwID, Ftd2xx.PCHAR SerialNumber, Ftd2xx.PCHAR Description, Ftd2xx.LPVOID Dummy);
	/**
	 * Original signature : <code>FT_STATUS FT_StopInTask(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:998</i>
	 */
	NativeLong fTStopInTask(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_RestartInTask(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1003</i>
	 */
	NativeLong fTRestartInTask(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_SetResetPipeRetryCount(FT_HANDLE, DWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1008</i>
	 */
	NativeLong fTSetResetPipeRetryCount(Ftd2xx.FT_HANDLE ftHandle, int dwCount);
	/**
	 * Original signature : <code>FT_STATUS FT_ResetPort(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1014</i>
	 */
	NativeLong fTResetPort(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_STATUS FT_CyclePort(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1019</i>
	 */
	NativeLong fTCyclePort(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>FT_HANDLE FT_W32_CreateFile(LPCTSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1029</i>
	 */
	Ftd2xx.FT_HANDLE fTW32CreateFile(Ftd2xx.LPCTSTR lpszName, int dwAccess, int dwShareMode, Ftd2xx.LPSECURITY_ATTRIBUTES lpSecurityAttributes, int dwCreate, int dwAttrsAndFlags, Ftd2xx.HANDLE hTemplate);
	/**
	 * Original signature : <code>BOOL FT_W32_CloseHandle(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1040</i>
	 */
	boolean fTW32CloseHandle(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>BOOL FT_W32_ReadFile(FT_HANDLE, LPVOID, DWORD, LPDWORD, LPOVERLAPPED)</code><br>
	 * <i>native declaration : ftd2xx.h:1045</i>
	 */
	boolean fTW32ReadFile(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPVOID lpBuffer, int nBufferSize, Ftd2xx.LPDWORD lpBytesReturned, Ftd2xx.LPOVERLAPPED lpOverlapped);
	/**
	 * Original signature : <code>BOOL FT_W32_WriteFile(FT_HANDLE, LPVOID, DWORD, LPDWORD, LPOVERLAPPED)</code><br>
	 * <i>native declaration : ftd2xx.h:1054</i>
	 */
	boolean fTW32WriteFile(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPVOID lpBuffer, int nBufferSize, Ftd2xx.LPDWORD lpBytesWritten, Ftd2xx.LPOVERLAPPED lpOverlapped);
	/**
	 * Original signature : <code>DWORD FT_W32_GetLastError(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1063</i>
	 */
	int fTW32GetLastError(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>BOOL FT_W32_GetOverlappedResult(FT_HANDLE, LPOVERLAPPED, LPDWORD, BOOL)</code><br>
	 * <i>native declaration : ftd2xx.h:1068</i>
	 */
	boolean fTW32GetOverlappedResult(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPOVERLAPPED lpOverlapped, Ftd2xx.LPDWORD lpdwBytesTransferred, boolean bWait);
	/**
	 * Original signature : <code>BOOL FT_W32_CancelIo(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1076</i>
	 */
	boolean fTW32CancelIo(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>BOOL FT_W32_ClearCommBreak(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1138</i>
	 */
	boolean fTW32ClearCommBreak(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>BOOL FT_W32_ClearCommError(FT_HANDLE, LPDWORD, LPFTCOMSTAT)</code><br>
	 * <i>native declaration : ftd2xx.h:1143</i>
	 */
	boolean fTW32ClearCommError(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPDWORD lpdwErrors, FTCOMSTAT lpftComstat);
	/**
	 * Original signature : <code>BOOL FT_W32_EscapeCommFunction(FT_HANDLE, DWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1150</i>
	 */
	boolean fTW32EscapeCommFunction(Ftd2xx.FT_HANDLE ftHandle, int dwFunc);
	/**
	 * Original signature : <code>BOOL FT_W32_GetCommModemStatus(FT_HANDLE, LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1156</i>
	 */
	boolean fTW32GetCommModemStatus(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPDWORD lpdwModemStatus);
	/**
	 * Original signature : <code>BOOL FT_W32_GetCommState(FT_HANDLE, LPFTDCB)</code><br>
	 * <i>native declaration : ftd2xx.h:1162</i>
	 */
	boolean fTW32GetCommState(Ftd2xx.FT_HANDLE ftHandle, FTDCB lpftDcb);
	/**
	 * Original signature : <code>BOOL FT_W32_GetCommTimeouts(FT_HANDLE, FTTIMEOUTS*)</code><br>
	 * <i>native declaration : ftd2xx.h:1168</i>
	 */
	boolean fTW32GetCommTimeouts(Ftd2xx.FT_HANDLE ftHandle, FTTIMEOUTS pTimeouts);
	/**
	 * Original signature : <code>BOOL FT_W32_PurgeComm(FT_HANDLE, DWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1174</i>
	 */
	boolean fTW32PurgeComm(Ftd2xx.FT_HANDLE ftHandle, int dwMask);
	/**
	 * Original signature : <code>BOOL FT_W32_SetCommBreak(FT_HANDLE)</code><br>
	 * <i>native declaration : ftd2xx.h:1180</i>
	 */
	boolean fTW32SetCommBreak(Ftd2xx.FT_HANDLE ftHandle);
	/**
	 * Original signature : <code>BOOL FT_W32_SetCommMask(FT_HANDLE, ULONG)</code><br>
	 * <i>native declaration : ftd2xx.h:1185</i>
	 */
	boolean fTW32SetCommMask(Ftd2xx.FT_HANDLE ftHandle, NativeLong ulEventMask);
	/**
	 * Original signature : <code>BOOL FT_W32_GetCommMask(FT_HANDLE, LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1191</i>
	 */
	boolean fTW32GetCommMask(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPDWORD lpdwEventMask);
	/**
	 * Original signature : <code>BOOL FT_W32_SetCommState(FT_HANDLE, LPFTDCB)</code><br>
	 * <i>native declaration : ftd2xx.h:1197</i>
	 */
	boolean fTW32SetCommState(Ftd2xx.FT_HANDLE ftHandle, FTDCB lpftDcb);
	/**
	 * Original signature : <code>BOOL FT_W32_SetCommTimeouts(FT_HANDLE, FTTIMEOUTS*)</code><br>
	 * <i>native declaration : ftd2xx.h:1203</i>
	 */
	boolean fTW32SetCommTimeouts(Ftd2xx.FT_HANDLE ftHandle, FTTIMEOUTS pTimeouts);
	/**
	 * Original signature : <code>BOOL FT_W32_SetupComm(FT_HANDLE, DWORD, DWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1209</i>
	 */
	boolean fTW32SetupComm(Ftd2xx.FT_HANDLE ftHandle, int dwReadBufferSize, int dwWriteBufferSize);
	/**
	 * Original signature : <code>BOOL FT_W32_WaitCommEvent(FT_HANDLE, PULONG, LPOVERLAPPED)</code><br>
	 * <i>native declaration : ftd2xx.h:1216</i>
	 */
	boolean fTW32WaitCommEvent(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.PULONG pulEvent, Ftd2xx.LPOVERLAPPED lpOverlapped);
	/**
	 * Original signature : <code>FT_STATUS FT_CreateDeviceInfoList(LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1245</i>
	 */
	NativeLong FT_CreateDeviceInfoList(IntByReference lpdwNumDevs);
	/**
	 * Original signature : <code>FT_STATUS FT_GetDeviceInfoList(FT_DEVICE_LIST_INFO_NODE*, LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1250</i>
	 */
	NativeLong fTGetDeviceInfoList(FT_DEVICE_LIST_INFO_NODE pDest, Ftd2xx.LPDWORD lpdwNumDevs);
	/**
	 * Original signature : <code>FT_STATUS FT_GetDeviceInfoDetail(DWORD, LPDWORD, LPDWORD, LPDWORD, LPDWORD, LPVOID, LPVOID, FT_HANDLE*)</code><br>
	 * <i>native declaration : ftd2xx.h:1256</i>
	 */
	NativeLong FT_GetDeviceInfoDetail(int dwIndex, IntByReference flags, IntByReference type, IntByReference id, IntByReference location, Pointer serialNumber, Pointer description, NativeLong ftHandleTemp);
	/**
	 * Original signature : <code>FT_STATUS FT_GetDriverVersion(FT_HANDLE, LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1273</i>
	 */
	NativeLong fTGetDriverVersion(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPDWORD lpdwVersion);
	/**
	 * Original signature : <code>FT_STATUS FT_GetLibraryVersion(LPDWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1279</i>
	 */
	NativeLong FT_GetLibraryVersion(IntByReference ver);
	/**
	 * Original signature : <code>FT_STATUS FT_Rescan()</code><br>
	 * <i>native declaration : ftd2xx.h:1285</i>
	 */
	NativeLong fTRescan();
	/**
	 * Original signature : <code>FT_STATUS FT_Reload(WORD, WORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1290</i>
	 */
	NativeLong fTReload(short wVid, short wPid);
	/**
	 * Original signature : <code>FT_STATUS FT_GetComPortNumber(FT_HANDLE, LPLONG)</code><br>
	 * <i>native declaration : ftd2xx.h:1296</i>
	 */
	NativeLong fTGetComPortNumber(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.LPLONG lpdwComPortNumber);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_ReadConfig(FT_HANDLE, UCHAR, PUCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:1307</i>
	 */
	NativeLong fTEEReadConfig(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.UCHAR ucAddress, Ftd2xx.PUCHAR pucValue);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_WriteConfig(FT_HANDLE, UCHAR, UCHAR)</code><br>
	 * <i>native declaration : ftd2xx.h:1314</i>
	 */
	NativeLong fTEEWriteConfig(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.UCHAR ucAddress, Ftd2xx.UCHAR ucValue);
	/**
	 * Original signature : <code>FT_STATUS FT_EE_ReadECC(FT_HANDLE, UCHAR, LPWORD)</code><br>
	 * <i>native declaration : ftd2xx.h:1321</i>
	 */
	NativeLong fTEEReadECC(Ftd2xx.FT_HANDLE ftHandle, Ftd2xx.UCHAR ucOption, Ftd2xx.LPWORD lpwValue);
	/**
	 * Original signature : <code>FT_STATUS FT_GetQueueStatusEx(FT_HANDLE, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:1328</i><br>
	 * @deprecated use the safer methods {@link #fTGetQueueStatusEx(ftd2xx.Ftd2xxLibrary.FT_HANDLE, java.nio.IntBuffer)} and {@link #fTGetQueueStatusEx(ftd2xx.Ftd2xxLibrary.FT_HANDLE, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	NativeLong fTGetQueueStatusEx(Ftd2xx.FT_HANDLE ftHandle, IntByReference dwRxBytes);
	/**
	 * Original signature : <code>FT_STATUS FT_GetQueueStatusEx(FT_HANDLE, DWORD*)</code><br>
	 * <i>native declaration : ftd2xx.h:1328</i>
	 */
	NativeLong fTGetQueueStatusEx(Ftd2xx.FT_HANDLE ftHandle, IntBuffer dwRxBytes);
	public static class PUCHAR extends PointerType {
		public PUCHAR(Pointer address) {
			super(address);
		}
		public PUCHAR() {
			super();
		}
	};
	public static class UCHAR extends PointerType {
		public UCHAR(Pointer address) {
			super(address);
		}
		public UCHAR() {
			super();
		}
	};
	public static class HANDLE extends PointerType {
		public HANDLE(Pointer address) {
			super(address);
		}
		public HANDLE() {
			super();
		}
	};
	public static class LPOVERLAPPED extends PointerType {
		public LPOVERLAPPED(Pointer address) {
			super(address);
		}
		public LPOVERLAPPED() {
			super();
		}
	};
	public static class FT_HANDLE extends PointerType {
		public FT_HANDLE(Pointer address) {
			super(address);
		}
		public FT_HANDLE() {
			super();
		}
	};
	public static class PCHAR extends PointerType {
		public PCHAR(Pointer address) {
			super(address);
		}
		public PCHAR() {
			super();
		}
	};
	public static class PVOID extends PointerType {
		public PVOID(Pointer address) {
			super(address);
		}
		public PVOID() {
			super();
		}
	};
	public static class LPLONG extends PointerType {
		public LPLONG(Pointer address) {
			super(address);
		}
		public LPLONG() {
			super();
		}
	};
	public static class LPSECURITY_ATTRIBUTES extends PointerType {
		public LPSECURITY_ATTRIBUTES(Pointer address) {
			super(address);
		}
		public LPSECURITY_ATTRIBUTES() {
			super();
		}
	};
	public static class LPWORD extends PointerType {
		public LPWORD(Pointer address) {
			super(address);
		}
		public LPWORD() {
			super();
		}
	};
	public static class PULONG extends PointerType {
		public PULONG(Pointer address) {
			super(address);
		}
		public PULONG() {
			super();
		}
	};
	public static class LPVOID extends PointerType {
		public LPVOID(Pointer address) {
			super(address);
		}
		public LPVOID() {
			super();
		}
	};
	public static class LPCTSTR extends PointerType {
		public LPCTSTR(Pointer address) {
			super(address);
		}
		public LPCTSTR() {
			super();
		}
	};
	public static class LPDWORD extends PointerType {
		public LPDWORD(Pointer address) {
			super(address);
		}
		public LPDWORD() {
			super();
		}
	}
}
