package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FTDCB extends Structure {
	/// sizeof(FTDCB)
	public int DCBlength;
	/// Baudrate at which running
	public int BaudRate;
	/// Conversion Error : fBinary:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fParity:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fOutxCtsFlow:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fOutxDsrFlow:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fDtrControl:2 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fDsrSensitivity:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fTXContinueOnXoff:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fOutX:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fInX:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fErrorChar:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fNull:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fRtsControl:2 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fAbortOnError:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : fDummy2:17 (This runtime does not support bit fields : JNA)
	/// Not currently used
	public short wReserved;
	/// Transmit X-ON threshold
	public short XonLim;
	/// Transmit X-OFF threshold
	public short XoffLim;
	/// Number of bits/byte, 4-8
	public byte ByteSize;
	/// 0-4=None,Odd,Even,Mark,Space
	public byte Parity;
	/// 0,1,2 = 1, 1.5, 2
	public byte StopBits;
	/// Tx and Rx X-ON character
	public byte XonChar;
	/// Tx and Rx X-OFF character
	public byte XoffChar;
	/// Error replacement char
	public byte ErrorChar;
	/// End of Input character
	public byte EofChar;
	/// Received Event character
	public byte EvtChar;
	/// Fill for now.
	public short wReserved1;
	public FTDCB() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"DCBlength", "BaudRate", "wReserved", "XonLim", "XoffLim", "ByteSize", "Parity", "StopBits", "XonChar", "XoffChar", "ErrorChar", "EofChar", "EvtChar", "wReserved1"});
	}
	public static class ByReference extends FTDCB implements Structure.ByReference {
		
	};
	public static class ByValue extends FTDCB implements Structure.ByValue {
		
	};
}
