package ftd2;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : ftd2xx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FTTIMEOUTS extends Structure {
	/// Maximum time between read chars.
	public int ReadIntervalTimeout;
	/// Multiplier of characters.
	public int ReadTotalTimeoutMultiplier;
	/// Constant in milliseconds.
	public int ReadTotalTimeoutConstant;
	/// Multiplier of characters.
	public int WriteTotalTimeoutMultiplier;
	/// Constant in milliseconds.
	public int WriteTotalTimeoutConstant;
	public FTTIMEOUTS() {
		super();
		//initFieldOrder();
	}
	protected List getFieldOrder() {
		return Arrays.asList(new String[]{"ReadIntervalTimeout", "ReadTotalTimeoutMultiplier", "ReadTotalTimeoutConstant", "WriteTotalTimeoutMultiplier", "WriteTotalTimeoutConstant"});
	}
	/**
	 * @param ReadIntervalTimeout Maximum time between read chars.<br>
	 * @param ReadTotalTimeoutMultiplier Multiplier of characters.<br>
	 * @param ReadTotalTimeoutConstant Constant in milliseconds.<br>
	 * @param WriteTotalTimeoutMultiplier Multiplier of characters.<br>
	 * @param WriteTotalTimeoutConstant Constant in milliseconds.
	 */
	public FTTIMEOUTS(int ReadIntervalTimeout, int ReadTotalTimeoutMultiplier, int ReadTotalTimeoutConstant, int WriteTotalTimeoutMultiplier, int WriteTotalTimeoutConstant) {
		super();
		this.ReadIntervalTimeout = ReadIntervalTimeout;
		this.ReadTotalTimeoutMultiplier = ReadTotalTimeoutMultiplier;
		this.ReadTotalTimeoutConstant = ReadTotalTimeoutConstant;
		this.WriteTotalTimeoutMultiplier = WriteTotalTimeoutMultiplier;
		this.WriteTotalTimeoutConstant = WriteTotalTimeoutConstant;
		//initFieldOrder();
	}
	public static class ByReference extends FTTIMEOUTS implements Structure.ByReference {
		
	};
	public static class ByValue extends FTTIMEOUTS implements Structure.ByValue {
		
	};
}
