<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<entry key="OP_MODE">0</entry>
<entry key="POS2">0</entry>
<entry key="POS1">9.45</entry>
<entry key="TUNLOCK">1</entry>
<entry key="SSC.MAIN">20	98	506	1176</entry>
<entry key="UNLOCK_PULSE">10</entry>
<entry key="STEP_NUMBER">100</entry>
<entry key="EXT2">0</entry>
<entry key="EXT1">0</entry>
<entry key="LensIndex">1</entry>
<entry key="TheoricExt">100</entry>
<entry key="CL"/>
<entry key="TSETTLE">0.5</entry>
<entry key="SSC.BELLOWS">-671	142	680	662</entry>
<entry key="CC">EDSDK	tpl:Canon EOS 100D@Jpeg Large	New Config	Canon EOS 100D	1	0	null	null	null	null	1048576		EDSDK	tpl:Canon EOS 5D Mark II@RAW	New Config	Canon EOS 5D Mark II	1	0	null	null	null	null	6291456		tpl:Canon EOS 5D Mark II@RAW		</entry>
<entry key="TIMELAPSE_NUMBER">0</entry>
<entry key="LENS.ARRAY">Zeiss Jena Tessar 50/2.8 @inf f2.8	50	2.8	0.6		Zeiss Jena Tessar 50/2.8 @inf f8	20	8	0.6		</entry>
<entry key="SSC.LIVEVIEW">94	816	699	547</entry>
<entry key="MIRRORLOCKUP">1</entry>
<entry key="SensorPixelX">5616</entry>
<entry key="SensorIndex">0</entry>
<entry key="RAIL.ARRAY">Stackshot	Stackshot	2	2	0	1.588	0.1	0	10	0	3200		Stackshot - Fast	Stackshot	6	2	0	1.588	0.1	0	10	0	3200		Virtual	Virtual	5	2	0.1	0	0	0	0	0	0		</entry>
<entry key="PICS">2</entry>
<entry key="FocalLens">20</entry>
<entry key="MeasuredExtFOV2">0</entry>
<entry key="CHECKVERSION">0</entry>
<entry key="MeasuredExtFOV1">2</entry>
<entry key="OUTPUTTXT">0</entry>
<entry key="PupilRatio">0.6</entry>
<entry key="fNumber">8</entry>
<entry key="SENSOR.ARRAY">Canon EOS 5D Mark II - 0 @ 0	36	0	5616	0		</entry>
<entry key="TPULSE">5</entry>
<entry key="TIMELAPSE_INTERVAL">0</entry>
<entry key="TOFF">1</entry>
<entry key="RANGE_END">10</entry>
<entry key="MAXCOC">2.5</entry>
<entry key="DOF_OVERLAP">1</entry>
<entry key="LOWER_LIMIT">-200</entry>
<entry key="STEP_SIZE">0.1</entry>
<entry key="RANGE_START">0</entry>
<entry key="RailIndex">2</entry>
<entry key="MeasuredFOV2">0</entry>
<entry key="MeasuredFOV1">36</entry>
<entry key="SensorWidth">36</entry>
<entry key="FRAMEBELLOWS">0</entry>
<entry key="UPPER_LIMIT">200</entry>
</properties>
