#Tue May 07 22:50:15 CEST 2013
OP_MODE=1
DOCKED=1
POS2=0
POS1=0
SSC.MAIN=0\t262\t483\t706
SensorHeight=24
STEP_NUMBER=8
LensIndex=0
TSETTLE=0.1
SSC.BELLOWS=0\t262\t687\t706
LENS.ARRAY=Zeiss Jena Flektogon 20/4 @inf f8\t20\t8\t0.6\t\tZeiss Jena Tessar 50/2.8 @inf f2.8\t50\t2.8\t0.6\t\tZeiss Jena Tessar 50/2.8 @inf f8\t50\t8\t0.6\t\t
RAIL=1
SensorPixelY=3\u00A0744
SensorPixelX=5\u00A0616
SensorIndex=0
PICS=1
FocalLens=20
SIMUL.HELPER=2\t2\t1.805\t
CHECKVERSION=1
OUTPUTTXT=1
PupilRatio=0.6
fNumber=8
SENSOR.ARRAY=Eos 5D MkII @RAW1\t36\t24\t5\u00A0616\t3\u00A0744\t\t
TPULSE=0.3
TIMELAPSE_INTERVAL=0
TOFF=0.1
RANGE_END=0
SSC.PREFS=350\t670\t300\t525
MAXCOC=2.5
DOF_OVERLAP=0.8
FTD2.HELPER=2\t2\t1.588\t0.1\t0\t10\t0\t0\t
LOWER_LIMIT=-200
RANGE_START=0
STEP_SIZE=0.473
MeasuredFOV2=0
MeasuredFOV1=36
SensorWidth=36
UPPER_LIMIT=200
